#!/bin/sh
# Public domain, 2012-2014 Simone Basso <bassosimone@gmail.com>

prefix=/var/local/qemu-kvm

DAEMONIZE="yes"
ECHO=""
OPTIONS="-enable-kvm -runas nobody -chroot $prefix/jail"
QEMU=`which qemu-system-x86_64`
SUDO=`which sudo`

usage() {
    cat << EOF
usage: qemu-kvm [-bfns] [-d display] [-i cdrom] machine

    -b          : do not use any display
    -d display  : specify display number to be used with view
    -f          : foreground mode (i.e. don't daemonize)
    -i cdrom    : specify path to cdrom file
    -n          : dry run
    -s          : snapshot mode

EOF
}

ARGS=$(getopt bd:fi:ns $*)
if [ $? -ne 0 ]; then
    usage 1>&2
    exit 1
fi
set -- $ARGS
while [ $# -gt 0 ]; do
    OPT=$1
    shift
    if [ "$OPT" = "-b" ]; then
        OPTIONS="$OPTIONS -display none"
    elif [ "$OPT" = "-d" ]; then
        OPTIONS="$OPTIONS -vnc 127.0.0.1:$1,lossy -usbdevice tablet"
        shift
    elif [ "$OPT" = "-f" ]; then
        DAEMONIZE=""
    elif [ "$OPT" = "-i" ]; then
        OPTIONS="$OPTIONS -cdrom $1"
        shift
    elif [ "$OPT" = "-n" ]; then
        ECHO="echo"
    elif [ "$OPT" = "-s" ]; then
        OPTIONS="$OPTIONS -snapshot"
    elif [ "$OPT" = "--" ]; then
        break
    else
        echo "FATAL: option parsing error" 1>&2
        usage 1>&2
        exit 1
    fi
done
if [ $# -ne 1 ]; then
    echo "FATAL: missing machine name"
    usage 1>&2
    exit 1
fi

if [ ! -r $prefix/etc/$1 ]; then
    echo "FATAL: machine not configured" 1>&2
    exit 1
fi

. $prefix/etc/$1

# Note: add at the beginning so we can override using cmdline
if [ "$NETDEV" != "user" ]; then
    OPTIONS="-netdev tap,script=$prefix/bin/ifup.$BRIDGE $OPTIONS"
else
    OPTIONS="-netdev user $OPTIONS"
fi
if [ "$MAC" = "auto" ]; then
    MAC=$(echo $1.varanasy.polito.it | md5sum | \
      sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
fi
OPTIONS="-net nic,model=$NIC_MODEL,macaddr=$MAC $OPTIONS"
OPTIONS="-drive file=$prefix/disk/$1.raw,index=0,media=disk,if=$DRIVE_IF $OPTIONS"
OPTIONS="-m $MEMORY $OPTIONS"
OPTIONS="-vga $VGA $OPTIONS"
if [ "$DAEMONIZE" = "yes" ]; then
    OPTIONS="$OPTIONS -daemonize"
fi

# XXX I don't remove the iptables rules
$ECHO $SUDO $QEMU $OPTIONS
