#!/bin/sh
# Public domain, 2013 Simone Basso <bassosimone@gmail.com>
# This command is provided, e.g., by tigervnc
vncviewer -preferredencoding tight -compresslevel 9 -qualitylevel 1 -lowcolorlevel 0 $@
